services:
  mainapp:
    build: ./src/
    depends_on:
      - postgres

  postgres:
    build: ./db/
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

