services:
  pythonapp:
    build: ./src/
    command: sh -c "python3 bot.py"
    depends_on:
      - postgres

  postgres:
    build: ./db/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

